name: widgetbook_models
description: A package that combines commonly used models from the widgetbook packages.
version: 0.0.6
homepage: https://www.widgetbook.io?utm_source=pub.dev&utm_medium=link&utm_campaign=widgetbook_models
repository: https://github.com/widgetbook/widgetbook
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://github.com/widgetbook/widgetbook/tree/main/packages/widgetbook_models

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  freezed_annotation: ^2.0.3
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^2.0.3
  test: ^1.18.2
  very_good_analysis: ^2.3.0
