name: widgetbook
description: A flutter storybook that helps professionals and teams to catalogue their widgets.
version: 2.1.0
homepage: https://www.widgetbook.io?utm_source=youtube&utm_medium=link&utm_campaign=widgetbook
repository: https://github.com/widgetbook/widgetbook
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://github.com/widgetbook/widgetbook/tree/main/packages/widgetbook
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  collection: ^1.15.0
  device_frame:
    git:
      url: https://github.com/zacherygentry/flutter_device_preview.git
      path: device_frame
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  go_router: ^3.0.5
  meta: ^1.7.0
  provider: ^6.0.2
  vector_math: ^2.1.0
  widgetbook_models:
    path: ../widgetbook_models

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3
  mocktail: ^0.1.4
  very_good_analysis: ^2.3.0

dependency_overrides:
  test_api: ^0.4.9

flutter:
  assets:
    - google_fonts/
  fonts:
    - family: Nunito
      fonts:
        - asset: google_fonts/Nunito-Black.ttf
        - asset: google_fonts/Nunito-BlackItalic.ttf
        - asset: google_fonts/Nunito-Bold.ttf
        - asset: google_fonts/Nunito-BoldItalic.ttf
        - asset: google_fonts/Nunito-ExtraBold.ttf
        - asset: google_fonts/Nunito-ExtraBoldItalic.ttf
        - asset: google_fonts/Nunito-ExtraLight.ttf
        - asset: google_fonts/Nunito-ExtraLightItalic.ttf
        - asset: google_fonts/Nunito-Italic.ttf
        - asset: google_fonts/Nunito-Light.ttf
        - asset: google_fonts/Nunito-LightItalic.ttf
        - asset: google_fonts/Nunito-Regular.ttf
        - asset: google_fonts/Nunito-SemiBold.ttf
        - asset: google_fonts/Nunito-SemiBoldItalic.ttf
