name: widgetbook_generator
description: A package to automate setup and maintanance of the widgetbook package by using code generation.
version: 2.0.1
homepage: https://www.widgetbook.io?utm_source=pub.dev&utm_medium=link&utm_campaign=widgetbook_generator
repository: https://github.com/widgetbook/widgetbook
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://github.com/widgetbook/widgetbook/tree/main/packages/widgetbook_generator
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^3.0.0
  build: ^2.1.0
  collection: ^1.15.0
  freezed_annotation: ^2.0.3
  glob: ^2.0.2
  json_annotation: ^4.4.0
  meta: ^1.7.0
  source_gen: ^1.1.0
  widgetbook_annotation:
    git:
      url: https://github.com/zacherygentry/widgetbook.git
      path: packages/widgetbook_annotation
  widgetbook_models:
    git:
      url: https://github.com/zacherygentry/widgetbook.git
      path: packages/widgetbook_models

dev_dependencies:
  build_runner: ^2.1.2
  freezed: ^2.0.3
  json_serializable: ^6.1.4
  test: ^1.18.2
  very_good_analysis: ^2.3.0
